Repository PaoloZesatiTec/Equipo-1, pull requests merged in 2025-05, with the labels that each got.

#26 Adding hitbox of player and coins
  game/js/platformer.js
Labels: Non-functional, Sprint 1, Front end

#27 Test gems
  game/js/platformer.js
Labels: duplicate, Functional, Sprint 1, Front end, Back end, Database, Videogame

#28 Test ladder
  game/js/levels.js
  game/js/platformer.js
Labels: duplicate, Functional, Sprint 1, Back end, Videogame

#29 Implementación de login y register forms sin backend
  .DS_Store
  game/html/login.html
  game/html/register.html
  game/js/menu.js
Labels: Non-functional, Sprint 1, Front end, Back end, Web

#32 enemy walking and hit box
  game/js/levels.js
  game/js/platformer.js
Labels: Sprint 2

#33 Ladder bugfix
  game/js/platformer.js
Labels: bug

#34 Bettered the UI of Gems and also added a heart counter with two lives…
  game/assets/Items/Gems/Gem Animations/gem_animation.png
  game/assets/Items/Gems/Gem_UI/gem.png
  game/assets/Items/Heart/heart.png
  game/js/levels.js
  game/js/platformer.js
Labels: Sprint 2

#35 better hitbox size
  game/js/platformer.js
Labels: bug

#36 Initial level generator, still a lot of work to do but good start
  game/html/index.html
  game/js/levelgenerator.js
  game/js/levels.js
  game/js/platformer.js
Labels: Sprint 2

#39 Algortimo de niveles (falta correción minima de escaleras en layers)
  .vscode/launch.json
  game/.DS_Store
  game/css/game.css
  game/css/style.css
  game/js/gameover.js
  game/js/levelgenerator.js
  game/js/platformer.js
Labels: Back end

#46 Test mage
  game/assets/stages/Map-1/PHOTO-2025-05-26-13-43-27.jpg
  game/js/enemies.js
  game/js/game_classes.js
  game/js/levelgenerator.js
  game/js/objects.js
  game/js/platformer.js
Labels: bug, Front end, Back end

#58 Escaleras fix
  game/js/platformer.js
Labels: bug, Non-functional, Sprint 3, Front end, Web, Videogame
