Repository PaoloZesatiTec/Equipo-1, pull requests merged in 2025-06, with the labels that each got.

#59 Added the MySQL script
  Database/Mage_tower.sql
Labels: Functional, Sprint 3, Back end, Web, Database

#61 Adding the login & register endpoint, already tested
  Servidor/app.js
  Servidor/package.json
Labels: Functional, Sprint 4, Back end, Web, Database

#62 Mejoras en página web y conexión con juego a html para marcar en que …
  game/assets/heart.svg
  game/css/style.css
  game/html/index.html
  game/js/platformer.js
Labels: Front end

#64 Bug fix
  game/js/enemies.js
  game/js/platformer.js
Labels: bug, Non-functional, Sprint 4, Front end, Videogame

#72 Some end point connections
  Servidor/app.js
  app.js
  game/html/index.html
  game/html/login.html
  game/html/stats.html
  game/js/Server_functions.js
  game/js/menu.js
  game/js/platformer.js
Labels: Functional, Sprint 5, Back end, Database
